apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: course-app-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: course-demo-app
    minReplicas: 2
    maxReplicas: 10
    metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60
