apiVersion: v1 
kind: Service
metadata:
  name: course-app-frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: courseapp
    env: prod
  type: LoadBalancer  
